name = "VLBIFiles"
uuid = "c1ebf4c8-f9d4-409a-8daf-7009448f4e6e"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.4.5"

[deps]
AccessorsExtra = "33016aad-b69d-45be-9359-82a41f556fd4"
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
DataManipulation = "38052440-ad76-4236-8414-61389b2c5143"
DateFormats = "44557152-fe0a-4de1-8405-416d90313ce6"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
InterferometricModels = "b395d269-c2ec-4df6-b679-36919ad600ca"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
PyFormattedStrings = "5f89f4a4-a228-4886-b223-c468a82ed5b9"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Uncertain = "b33f403f-199b-472b-b9d0-1cd2092892d0"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAngles = "6fb2a4bd-7999-5318-a3b2-8ad61056cd98"
UnitfulAstro = "6112ee07-acf9-5e0f-b108-d242c714bf9f"
VLBIData = "679fc9cc-3e84-11e9-251b-cbd013bd8115"

[weakdeps]
AxisKeysExtra = "b7a0d2b7-1990-46dc-b5dd-87820ecd1b09"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
RectiGrids = "8ac6971d-971d-971d-971d-971d5ab1a71a"
SkyCoords = "fc659fc5-75a3-5475-a2ea-3da92c065361"

[extensions]
InterpolationsExt = "Interpolations"
PyCallExt = "PyCall"
RectiGridsAxisKeysExtraExt = ["RectiGrids", "AxisKeysExtra"]
SkyCoordsExt = "SkyCoords"

[compat]
AccessorsExtra = "0.1.77"
AxisKeys = "0.1, 0.2"
AxisKeysExtra = "0.1.22"
DataManipulation = "0.1.12"
DateFormats = "0.1.12"
Dates = "1"
DelimitedFiles = "1.9"
Dictionaries = "0.4.5"
FITSIO = "0.17.5"
InterferometricModels = "0.1.24"
Interpolations = "0.15"
PrecompileTools = "1"
PyCall = "1.92"
PyFormattedStrings = "0.1.10"
RectiGrids = "0.1.0"
Reexport = "1.2.2"
SkyCoords = "1.5.3"
StaticArrays = "1.0"
Statistics = "1"
StructArrays = "0.6.4, 0.7.1"
Tables = "1.4"
Uncertain = "0.1.0"
Unitful = "1.5"
UnitfulAngles = "0.6.2, 0.7"
UnitfulAstro = "1.0"
VLBIData = "0.5"
julia = "1.10"
